---
title: "Whitehead Secret Santa"
author: "Amy Whitehead"
date: "27 September 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r load libraries}
require(tidyverse)
require(lubridate)
require(gmailr)

# gargle::oauth_app_from_json("credentials.json")
gm_auth_configure(path = "credentials_v3.json")

# Authenticate with the tokens in the copied cache
gm_auth(email = TRUE, cache = ".secret")

```

```{r load data}

presents <- read.csv("data/Whitehead Secret Santa.csv", stringsAsFactors = F)

```

```{r santas little helper}

SantasLittleHelper <- function(myFrame,guestList,conflictCols = NULL){
  myTest <- TRUE
  nElves <- 0
  
  while (myTest == TRUE){
    myOut <- data.frame(guest = myFrame[,guestList],
                        giftee = sample(myFrame[,guestList],
                                        replace = FALSE,
                                        size=nrow(myFrame))
                        )
    
    # check that guests haven't drawn themselves
    guestTest<- unlist(lapply(1:nrow(myOut),function(x) {
      myOut$giftee[x] == myFrame[x,guestList]
      }))
    
    # check for gifting conflicts
    if(!is.null(conflictCols)){
      
    conflictTest <- unlist(lapply(1:nrow(myOut),function(x) {
      grepl(myOut$giftee[x],myFrame[x,conflictCols])
      }))
    
    myTest <- any(c(guestTest,conflictTest[!is.na(conflictTest)]))
    
    } else{
      myTest <- any(guestTest)
    }
    
    # count the number of iterations needed to avoid conflicts
    nElves <- nElves + 1
  }
  
  base::message(paste(nElves,"elves were needed to generate the gift list"))
  return(myOut)
}

```

```{r assign presents}

this_year <- SantasLittleHelper(presents,"guest",
                   conflictCols = c("partner","presents2020","presents2021","presents2022"))


presents %>% 
  left_join(this_year) %>% 
  rename(!!quo_name(paste0("presents",year(Sys.Date()))) := giftee) %>% 
  write.csv("data/Whitehead Secret Santa.csv",row.names=F)

```

```{r send email}

map(this_year$guest, function(myGuest){
  
  test_email <- gm_mime() %>%
  gm_to(presents %>% filter(guest %in% myGuest) %>% pull(email)) %>%
  gm_from("amylouisewhitehead@gmail.com") %>%
  gm_subject("2023 Whitehead Secret Santa") %>%
  gm_text_body(paste("Kia ora", myGuest,",
                     
This year's Whitehead Christmas includes a Secret Santa gift, where everyone has been randomly allocated one person for whom they have to buy a gift. The gift is given on behalf of everyone else and could be as serious or silly as you like as long as it is less than $50 and isn't plastic crap. Note that small children have been excluded from this - feel free to spoil them rotten at your own discretion!

Your giftee is:",this_year %>% filter(guest %in% myGuest) %>% pull(giftee),"

Meri kirimihete
Santa xxx"))

gm_create_draft(test_email)

})



```

